sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  - DOCKER_USERNAME='djfuentes+github'
  - DOCKER_PASSWORD='9FZ4STF0H3LX965A1CN6ANCB9F8R1ZCWP9O3XM6FHYK6A3I3N7AFBPV65LJU257C'

branches:
  only:
  - master
  - all-services-developed

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version

install: 
  - yarn install

before_script:
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 10
  - make brand
  - make package

script:
  - make qa

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker
    - env: SERVICE=recipes-id-generator
      services:
        - docker